-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.30 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for wpu_blog
CREATE DATABASE IF NOT EXISTS `wpu_blog` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `wpu_blog`;

-- Dumping structure for table wpu_blog.categories
CREATE TABLE IF NOT EXISTS `categories` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `categories_name_unique` (`name`),
  UNIQUE KEY `categories_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table wpu_blog.categories: ~2 rows (approximately)
INSERT IGNORE INTO `categories` (`id`, `name`, `slug`, `created_at`, `updated_at`) VALUES
	(1, 'Web Programming', 'web-programming', '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(2, 'Web Design', 'web-design', '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(3, 'Personal', 'personal', '2023-10-31 09:25:18', '2023-10-31 09:25:18');

-- Dumping structure for table wpu_blog.failed_jobs
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table wpu_blog.failed_jobs: ~0 rows (approximately)

-- Dumping structure for table wpu_blog.migrations
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table wpu_blog.migrations: ~0 rows (approximately)
INSERT IGNORE INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(1, '2014_10_12_000000_create_users_table', 1),
	(2, '2014_10_12_100000_create_password_reset_tokens_table', 1),
	(3, '2019_08_19_000000_create_failed_jobs_table', 1),
	(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
	(5, '2023_10_31_120504_create_posts_table', 1),
	(6, '2023_10_31_130459_create_categories_table', 1);

-- Dumping structure for table wpu_blog.password_reset_tokens
CREATE TABLE IF NOT EXISTS `password_reset_tokens` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table wpu_blog.password_reset_tokens: ~0 rows (approximately)

-- Dumping structure for table wpu_blog.personal_access_tokens
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table wpu_blog.personal_access_tokens: ~0 rows (approximately)

-- Dumping structure for table wpu_blog.posts
CREATE TABLE IF NOT EXISTS `posts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `category_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `published_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `posts_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table wpu_blog.posts: ~20 rows (approximately)
INSERT IGNORE INTO `posts` (`id`, `category_id`, `user_id`, `title`, `slug`, `excerpt`, `body`, `published_at`, `created_at`, `updated_at`) VALUES
	(1, 2, 1, 'Debitis laborum ullam sint.', 'aut-est-et-sapiente-consequatur-amet-facilis', 'Molestiae rerum ducimus ad tempore. Quis odit aut sapiente tempora alias quod id. Quasi quo et ab ullam ex non.', '<p>Ratione eum dolor impedit voluptas labore aut. Aut fugit a delectus eaque aut nobis.</p><p>Consequuntur velit qui voluptatum earum sit quos error non. Id sequi cumque est eaque reiciendis quo quia. Pariatur assumenda laboriosam iste dolores hic. Rerum quia maxime dolores deleniti dicta et labore.</p><p>Omnis praesentium aut qui non ea. Voluptas sint ducimus nesciunt molestias dolore dolores non. Numquam facilis non quibusdam architecto.</p><p>Ea enim sint aut repellendus atque quia esse. Id amet dolorum consequuntur nemo asperiores similique accusantium. Molestiae ea rerum maxime ut maxime facilis quibusdam. Molestiae dolorem dolor tempora. Perspiciatis facere eum et.</p><p>Ratione eum voluptatem rerum sit. Sequi tenetur natus aut quod natus laborum. Ipsa libero quia et alias rem ut. Vel vero qui et quibusdam.</p><p>Eum sit maiores deserunt. Consequuntur eum aut et impedit. Natus laudantium tenetur voluptatibus.</p><p>Sit hic nam molestiae quasi sunt in. Ab tempora ab qui. Cum dolores sit porro aspernatur molestiae.</p><p>Ducimus nostrum exercitationem rem voluptates. Voluptas quidem quam consequatur fugit. Aperiam velit sed qui voluptatibus quis consequatur.</p><p>Magnam repellat aut distinctio id sint rerum perferendis. Provident impedit excepturi quas et libero. Enim soluta saepe sit. Omnis qui ullam ea iste.</p><p>Aut itaque saepe est voluptas architecto. Iusto porro qui aut nulla consequatur sit numquam. Est esse quia est blanditiis et velit.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(2, 1, 1, 'Suscipit qui beatae incidunt explicabo corporis dolorem quis.', 'voluptatem-quis-est-et', 'Autem dolor id id necessitatibus veritatis consequatur. Soluta in est vero. A eius qui sit delectus quos fugiat.', '<p>Et fugit vel impedit. Qui et nulla veniam ut et deserunt voluptate atque.</p><p>Illum qui nesciunt eveniet placeat quo deleniti. Autem odio expedita non sit et ullam. Ea sit nulla sed natus aliquid.</p><p>Qui dolores ut harum harum. Libero et iste quia qui dolores repudiandae magni. Iusto blanditiis minima veniam consequatur velit.</p><p>Repudiandae nemo aut asperiores rerum. Omnis quos repellendus non laborum et minus. Alias itaque sit accusantium iste vitae. Commodi voluptatum dolores ut consequatur.</p><p>Est eaque vitae velit aut qui dignissimos voluptatem. Facere qui dicta modi. Eveniet eaque facere beatae veniam modi reiciendis dolorem. Illum odit aliquam aliquid.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(3, 1, 1, 'Saepe nobis vel eveniet natus eaque quo.', 'aspernatur-aperiam-nam-eius-et-saepe-ducimus', 'Aut deserunt rerum et et placeat accusamus. Eveniet incidunt officiis voluptatem vel magnam. Ab assumenda consectetur saepe aspernatur totam voluptatem error.', '<p>Voluptatem autem iusto rem soluta. Aut ipsam porro est reiciendis maiores labore.</p><p>Sed numquam est molestiae nostrum. Ducimus provident aut occaecati ut et praesentium recusandae. Ea molestiae voluptatibus quis sed sed vitae in. Modi aspernatur saepe dolores labore rerum nobis.</p><p>Voluptatem fugit exercitationem aut est. Dignissimos incidunt ut aliquid placeat quis earum. Ratione eligendi occaecati quod officia eius perspiciatis quae.</p><p>Harum voluptate sunt temporibus quod. Unde velit nisi eum voluptatem. Quisquam optio corporis totam et numquam. Non earum nihil tempore id explicabo assumenda. Et molestiae enim suscipit ea.</p><p>Aspernatur iure ut tempore qui perferendis. Repellendus commodi ratione laborum illum ut ut facilis. Autem asperiores ullam nobis dolore doloribus consequatur aspernatur eius.</p><p>Tempora non ratione iste est. Laborum quia est libero aut error. Soluta et rerum veniam sequi iure dicta illum ut.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(4, 2, 3, 'Nesciunt qui aut.', 'maiores-itaque-iure-dolores-dicta-dolorem-totam', 'Nihil est sapiente sit quas. Earum nam vitae a quis sequi ab enim. Autem aut natus rem blanditiis optio dolore.', '<p>Iure et ad sint occaecati voluptas. Et ut hic voluptatum similique ullam facilis est. Sequi voluptatem autem nihil saepe beatae blanditiis quam.</p><p>Ad aut quis sint qui et voluptatem commodi. Quisquam et sit ducimus est sunt quis. Asperiores quibusdam consequatur rem ut quos deserunt nostrum quam.</p><p>Odit quo enim dolorem nihil reiciendis provident. Qui ut aspernatur assumenda et eveniet non cum. Molestiae ut sint occaecati aut.</p><p>Quis commodi voluptate veniam quidem quia dolor aspernatur. Voluptatem omnis dignissimos quia rerum. Odio minus eius incidunt autem officia.</p><p>Voluptatem aspernatur nisi ab doloremque dolor. Quis voluptatum et earum ab. Eos beatae modi sunt voluptate nihil et. Porro ratione quae et molestiae laudantium sint sed repellat.</p><p>Culpa maiores ad corporis eum totam illum repudiandae. Sit delectus laboriosam voluptatibus doloremque voluptatem. Totam consequatur dicta dicta assumenda consectetur neque amet. Alias tempore eos beatae et provident voluptatibus.</p><p>Necessitatibus quibusdam ut voluptatem numquam qui incidunt et soluta. Inventore eos nesciunt nisi rerum. Modi omnis at laborum quos dolorem. Sit praesentium ab dolorem.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(5, 2, 3, 'Adipisci quia culpa.', 'ut-ipsa-molestias-aspernatur-omnis-ut-aspernatur', 'Non architecto architecto maxime ducimus repellat reiciendis quod molestiae. Esse tempora aut maiores. Voluptas sit vitae ratione mollitia ut earum temporibus. Dolores eligendi mollitia enim nihil nihil.', '<p>Voluptate eos et harum maiores asperiores qui. Cumque natus modi a perspiciatis. Dolor in accusantium officia accusantium. Aut autem nulla facilis. Autem molestiae fuga eaque.</p><p>Error voluptatem voluptatem vel doloribus facere. Pariatur ut rem rerum aut. Repellat ipsa ex ut voluptatum.</p><p>Id nihil dolorem adipisci cupiditate reprehenderit hic tempore. Quas dolor praesentium sed cumque quibusdam.</p><p>Et dolorem pariatur explicabo perferendis incidunt sunt illo. Velit perferendis modi aut et. Consectetur quis praesentium sequi et.</p><p>Velit quis tempora quo et enim perferendis. Dicta voluptatem sit dolorem aut sunt non. Laudantium esse qui est nisi repellat eum quis. Laudantium rerum perspiciatis natus sequi fuga reprehenderit aliquam.</p><p>Sapiente voluptatum velit dolores in eum voluptates commodi. Doloremque provident dolore adipisci velit eius porro enim.</p><p>Quibusdam perferendis doloribus est aliquam totam. Et asperiores quas libero assumenda. Rerum modi sint quia dolore aliquid asperiores atque numquam. Eaque repellat omnis magni vel omnis magni mollitia.</p><p>Quo odio illo consequatur cupiditate. Velit amet sed officiis iste ipsa ipsam. Tempora nihil debitis maxime ut quia enim corporis omnis. Maxime consectetur consequuntur id assumenda nihil id aut.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(6, 1, 2, 'Magni fugit soluta ad aut necessitatibus quia.', 'aut-enim-nostrum-sit-minus-suscipit', 'Est architecto non aut optio rem. Sint itaque ut libero qui. Rem iure ad velit sint dolores numquam. Vel porro libero sint placeat et.', '<p>In laborum eum quidem. Non qui tempore quasi. Voluptates ratione hic dolorum ab error ut.</p><p>Quam et soluta distinctio dolor ad et voluptas. Accusamus ea nemo quod ullam provident similique. Omnis neque molestiae ut ut. Provident aliquam occaecati omnis.</p><p>Rem animi necessitatibus omnis quia veritatis ea. Consectetur qui molestiae rerum possimus. Eos recusandae beatae optio et occaecati voluptas quisquam. Ea ducimus aperiam commodi cum unde et vero ipsum.</p><p>Magnam et ut distinctio repellat sunt eligendi. Vitae rerum cupiditate ut voluptatibus non. Consectetur architecto pariatur amet ut quis voluptatem. Et facere non ea molestiae quam.</p><p>Quae eum alias molestias sint incidunt odit assumenda. Quasi et nesciunt est inventore. Consequatur a labore enim facere enim aut.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(7, 1, 3, 'Debitis aliquid occaecati deleniti.', 'quidem-unde-veniam-perspiciatis-dolores-et-quia', 'Odio unde reiciendis dolorum. Et perspiciatis eveniet facere dolores. Consequatur consequatur incidunt consequatur vero velit.', '<p>Vitae repudiandae nemo necessitatibus. Maxime qui distinctio et nulla. Veritatis in nesciunt iusto est quis et maiores. Voluptatem et ut consequuntur aliquam.</p><p>Deleniti possimus et neque a aliquam et est incidunt. Molestiae rerum quis possimus consectetur accusamus. Vel autem ratione est dolor quis iusto qui. Magni est adipisci mollitia id cum deserunt dicta. Eos impedit officia omnis similique adipisci reiciendis.</p><p>Impedit consectetur autem rerum earum aliquam. Esse ipsa qui quibusdam sed aut facilis et. Sit illo voluptas ducimus aliquam quo. Vero blanditiis maxime totam sed ad. Consequatur ab ipsum voluptas beatae et.</p><p>Aut quidem omnis quisquam expedita fugit. Ut dolores excepturi voluptate. Vitae et assumenda nobis sit possimus maxime nulla.</p><p>Voluptates molestias molestiae iusto et. Quia et sunt voluptates nobis id molestiae laborum consectetur. Impedit iure mollitia itaque velit autem. Quo tempora cum pariatur ea cupiditate.</p><p>Enim sed quos incidunt numquam. Et culpa et unde consequuntur tempore. Voluptatem provident quibusdam nesciunt ullam eum et harum. Animi temporibus ullam sequi vel repellat qui voluptatum illum.</p><p>Ipsa corrupti id est. Vitae est nesciunt a atque est ab alias. Voluptate enim dolor id tenetur nam rerum qui.</p><p>Reprehenderit id magni earum ut et. Numquam ut nostrum reprehenderit dolorem provident tempore molestiae. Minima nihil quasi tempora ipsum voluptatibus minima. Quia ut pariatur soluta ut.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(8, 1, 1, 'Quae libero sit et.', 'rem-ullam-saepe-voluptatibus', 'Voluptatem alias ad impedit sit. Quaerat corrupti neque accusantium inventore. Optio et cumque amet quam nesciunt dolores.', '<p>Aut sit omnis debitis velit velit. Possimus atque voluptas repudiandae doloribus atque. Sit nulla perferendis eius omnis fugiat blanditiis necessitatibus. Repellat autem et officiis ratione.</p><p>Rerum cum quia qui delectus nostrum omnis natus. Veniam fugit quia consequatur fuga exercitationem consequatur libero. Sed consequatur sint temporibus. Voluptatem sint natus inventore.</p><p>Voluptatem assumenda consequatur eum mollitia quo. Eum commodi dolorem molestiae aperiam minima. Omnis et eveniet ratione voluptas et neque necessitatibus eum. Accusamus ea et voluptatibus recusandae in.</p><p>Eos molestiae fuga facilis doloremque aut. Molestias maiores magni vel velit quod fugit doloremque velit. Corporis consectetur vitae et quis rerum quis. Repellendus aliquid nihil rerum.</p><p>Sed inventore odit commodi voluptatem numquam. Impedit aut ipsum animi mollitia rerum. Nulla sed repellendus est est accusantium.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(9, 2, 3, 'Beatae iure quidem nobis dignissimos.', 'totam-iure-accusantium-architecto-sequi-voluptas-ullam-in-ut', 'Aliquam amet et pariatur sed dolores error repellendus. Recusandae dicta accusantium sequi eligendi error velit unde. Tenetur possimus fugiat dolorem perferendis.', '<p>Ullam ut itaque sed commodi voluptas ipsum. Unde dolores quia ut ipsum qui nostrum sunt. Quasi nostrum asperiores odio.</p><p>Dolorem facere rerum et eaque explicabo quo facere. Et id dolorem perferendis consectetur laborum sunt. Beatae est autem veritatis odit ipsum.</p><p>Repellat suscipit quidem recusandae possimus. Soluta et at repellendus aliquam ex consequatur. Sit omnis dolores nemo vel similique quasi et. Quibusdam aperiam quam rerum consectetur.</p><p>Non a soluta sequi alias id sed nam. Possimus et vitae autem. Nam cumque blanditiis dolor. Est eos et nihil.</p><p>Dolorem aut qui corrupti amet at magni. Veniam ab harum nihil ut. Sed eum quas placeat libero nihil est sequi.</p><p>Iste et excepturi amet molestias. Temporibus excepturi ut facilis optio officia aspernatur. Consequuntur qui animi nobis qui. Consequatur a laboriosam quasi ratione ratione asperiores.</p><p>Error sint debitis est cupiditate incidunt voluptatem. Est sed rem commodi illum culpa officiis exercitationem. Recusandae commodi est ea voluptatibus deleniti.</p><p>Distinctio minima ullam ipsum nulla soluta nulla. Et voluptatem repudiandae est vitae occaecati. Qui voluptas fugiat ad eaque neque repudiandae voluptatum est. Vel aut consectetur necessitatibus aut.</p><p>Itaque et voluptates omnis ut earum. Dolores laborum tenetur odio vero. Aut tempore modi ut tempora quis magnam. Dignissimos voluptatum officia tempore voluptatem accusantium est nihil.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(10, 2, 1, 'In ut quis similique.', 'facilis-quidem-adipisci-labore-neque-ut-soluta-aut-sed', 'Error possimus hic nobis doloremque natus recusandae in. Sed fugit vel temporibus tenetur mollitia impedit similique. Sint voluptatem ut voluptatem rerum omnis ut provident. Officia praesentium et illo dolores natus nesciunt.', '<p>Rerum dolor unde quo eius quisquam et aperiam. Impedit aut eum ut dignissimos enim dolores voluptas ut. Rem corrupti doloribus ut molestias laudantium sit dolorem.</p><p>Optio ipsa dolores et. Illum id fuga iusto enim debitis. Culpa et adipisci nobis ut explicabo ab tempore quisquam. Et molestias corporis necessitatibus qui nihil ut harum.</p><p>Maxime aut dolorem enim qui corrupti. Aut soluta et sequi qui quis minima. Molestias veritatis quis quibusdam libero. Corrupti quidem eos velit molestiae quasi eaque eveniet.</p><p>Voluptas dolorem aut esse ea iure. Deserunt similique rerum expedita ea repellendus et quis. Voluptatem earum perspiciatis distinctio aperiam. Iste et debitis dicta ipsam aut. Eos velit ut aut quis nostrum eum dolorem.</p><p>Itaque velit omnis non voluptas asperiores amet et. Animi laudantium quia quam voluptatem ab occaecati. Voluptas corporis ullam quidem earum quod vitae vero.</p><p>Possimus odio maiores et sit molestiae corrupti cupiditate. Natus enim ducimus animi dolor enim dolore. Minus ex ipsum commodi soluta velit repellendus. Totam tempore accusantium ratione dignissimos nulla soluta.</p><p>Dolor in non non neque omnis a commodi. Et sunt et quis autem. Quasi nihil nihil dignissimos et tempora molestiae placeat.</p><p>Molestiae et cum voluptas. Explicabo totam debitis cupiditate et id in. Assumenda itaque accusantium quas ab mollitia. Voluptas perferendis veritatis blanditiis id quod sed inventore.</p><p>Iusto cupiditate officiis veritatis dolor cumque modi. Aliquid iure esse mollitia et praesentium aspernatur molestiae. Sequi esse vel omnis magnam et ut.</p><p>Et consequatur tempore quas ratione. Maiores et eum iusto ratione nisi voluptatum laborum nulla. Aut perspiciatis et quo odio. Ab consequatur hic ipsum. Quae et nostrum molestiae delectus totam.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(11, 3, 3, 'Asperiores perferendis est unde veritatis rem sed vel officia.', 'aliquam-distinctio-quia-culpa-quia-ipsum-aut-quae-recusandae', 'Nesciunt quidem quis maiores beatae. Voluptates dolorem expedita tempora distinctio in dolorem. Eius et nesciunt aut quibusdam explicabo.', '<p>Itaque aliquam doloribus exercitationem. Vel atque totam in eum perspiciatis est ipsam magnam. Delectus eaque culpa voluptatibus blanditiis ut a.</p><p>Quae eaque repudiandae natus suscipit. Facere officia reprehenderit quibusdam assumenda voluptas doloremque. Aut asperiores dolorum nobis voluptas quasi et reprehenderit qui.</p><p>Qui rerum autem temporibus voluptas. Dolore reprehenderit odio excepturi molestias et et. Et culpa eveniet corporis numquam. Ducimus eligendi totam maxime maxime. Nemo quia aspernatur veritatis sed id qui error.</p><p>Ut omnis est sed veniam quas architecto recusandae. Nisi sit sint dicta sed ut. Optio repellat laudantium deserunt velit fuga qui quia.</p><p>Vitae aperiam sunt repudiandae pariatur et nobis voluptate. Et minima eos et quis quos. Assumenda eius quia aut saepe sed voluptatem rerum et. Vel et sunt corporis voluptatum. Atque provident voluptas qui.</p><p>Pariatur harum nisi voluptatem nihil est dolore dolorum doloremque. Qui deserunt officiis quis enim placeat quia sunt. Corporis provident eum odio non dolorum quam ad nesciunt. Quia quasi nostrum dignissimos adipisci.</p><p>Ut non repudiandae quo voluptatum. Id occaecati doloribus mollitia minus voluptates. Qui dicta rerum sit vel omnis mollitia ad facilis. Sed hic quisquam reprehenderit vel deleniti totam sunt.</p><p>Nemo recusandae et in sit hic. Repudiandae neque dignissimos est minima id consectetur.</p><p>Ratione qui placeat suscipit. Repellendus quam rem suscipit dolorem voluptatum. Eveniet error ut recusandae quidem rerum inventore.</p><p>Velit sit voluptatem voluptatem non itaque iste libero. In at et ducimus est voluptatem ut fugiat. Aut est nihil nesciunt hic iusto. Sunt consequuntur voluptatibus dicta repellat sint nihil fuga.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(12, 3, 2, 'Ea expedita fuga est quia voluptatem et et dolorem aut.', 'sunt-et-deleniti-aliquid-quos-ullam-illo', 'Quia ut incidunt quisquam et iusto non in. Laborum hic dolore aut suscipit. Aut quisquam inventore ipsam molestias earum eius. Laborum voluptatem amet deserunt fugiat repudiandae eveniet.', '<p>Dolores aut et veniam laboriosam rem. Dolores delectus eos excepturi. Qui voluptas aut distinctio assumenda reiciendis saepe eos. Est quas commodi accusamus perferendis omnis.</p><p>Dicta nihil aliquid fuga aut rem corrupti. Culpa sed est minima optio numquam odit aut. Repudiandae non aut architecto excepturi possimus esse rerum. Inventore quaerat minus necessitatibus autem quis temporibus pariatur.</p><p>Consequuntur est quia voluptas libero id consequatur quibusdam. Alias et delectus eveniet. Dolorum aspernatur magnam cum dolores nihil maxime.</p><p>Ut in consectetur aut cupiditate a. Porro voluptate unde vel et est sit commodi. Est earum omnis aliquid quis molestias. Enim et non atque corporis.</p><p>Iusto doloribus dolor optio quia impedit. Possimus dolor natus voluptates modi. Tenetur magnam repellendus voluptatem vitae aliquam qui.</p><p>Ducimus reiciendis dolores voluptate quae ducimus ullam. Et laborum ea pariatur ad est saepe. Quo consequatur aut laborum quos sequi rerum.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(13, 3, 2, 'Nobis quasi sit nobis.', 'voluptas-hic-iure-non-qui-et-quia-voluptate', 'Voluptate ducimus dolor sapiente nulla facere suscipit molestias dolorem. Ea nemo et architecto ex ut ipsa et. Tempora aliquid tenetur distinctio saepe incidunt.', '<p>Ad sapiente deleniti consequatur sit. Vero suscipit blanditiis a est. Praesentium ex facere sit.</p><p>Neque dolorem quam aut ut rerum possimus. Fuga repellat ullam velit est officia. Dolores sed rerum delectus repellat alias.</p><p>Id molestias fugit at repellat voluptas eum et. Aliquam quod facilis occaecati adipisci recusandae. Illum qui corrupti aspernatur quis reiciendis.</p><p>Quibusdam atque rerum ut consequatur. Cum vero quam error in quo accusantium nihil aut. Consequuntur incidunt repellendus blanditiis saepe odio aliquam aut.</p><p>Illum assumenda maiores sint repudiandae voluptate ut. Vitae laborum voluptate et nostrum sint perferendis aut. Dolores reprehenderit aperiam consequatur veniam. Minus ducimus eius sit expedita amet.</p><p>Dolorem quia et vitae omnis omnis placeat cum. Et et et at exercitationem nulla. Doloremque cupiditate eos dignissimos quia alias.</p><p>Laborum vitae molestias in aut a assumenda consectetur. Dolor officia sit sit magnam at natus. Et optio eius molestiae omnis. Alias repellendus enim repudiandae.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(14, 3, 1, 'Placeat nam numquam beatae aliquid ratione praesentium.', 'nemo-facere-qui-dolor-et-ex-eos', 'Harum deleniti laboriosam debitis occaecati. Corrupti sequi cumque aut consequatur. Dolorem voluptatum doloribus autem quod eius veritatis. Id molestiae ad qui.', '<p>Aut et beatae fugiat ut deserunt. Occaecati a voluptate explicabo eius doloribus est corrupti. Distinctio occaecati incidunt et dicta est et. Amet porro totam et architecto rerum hic quae accusamus. Repellat magnam hic sit optio minus ea veniam.</p><p>Natus debitis amet in. Provident quia a voluptatem quo. Autem voluptatem molestias et.</p><p>Aliquam consequatur quia architecto tenetur fugiat. Pariatur voluptatem quia aut corrupti quibusdam mollitia. Nulla ea inventore officia repudiandae perferendis qui consequuntur magnam.</p><p>Non quod nihil porro id. Recusandae rerum distinctio rerum incidunt in alias a. Recusandae officia nam minima ipsa architecto. Accusamus est quibusdam enim voluptas ex molestias.</p><p>Enim voluptas fuga sint. Et facilis possimus perferendis distinctio dolor veritatis placeat. Eum eum eum aspernatur quidem.</p><p>Dolores qui pariatur vel tempore doloremque reiciendis sed. Saepe non iste id veritatis sed corporis amet. Corporis cum consequatur iste qui est illo sequi alias.</p><p>Aut dolorem necessitatibus enim et. Excepturi sint porro quasi ratione accusamus. Sint possimus doloremque et neque neque iusto fuga. Omnis ratione possimus est est.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(15, 2, 2, 'Qui aut distinctio qui pariatur omnis quia.', 'et-asperiores-perspiciatis-est-expedita', 'Veniam inventore quod amet fuga corrupti aut. Consectetur quam mollitia et aut illo. Omnis ea neque non quod.', '<p>Voluptates quaerat dolorem voluptates iure sed. Delectus rerum ratione quaerat et. Dolorem sed enim cumque iure enim ipsam. Officiis voluptatem accusamus fugiat perspiciatis eos non.</p><p>Reprehenderit temporibus consequatur veniam molestias sed dolore consequuntur quibusdam. A recusandae a ipsam eaque perspiciatis voluptates rerum. Odio dolorem quaerat debitis libero.</p><p>Dicta culpa reiciendis iure et rem. Provident nisi id perferendis ratione et et neque. Placeat in numquam aut aut. Exercitationem aliquid sunt sint aut recusandae praesentium at. In inventore et blanditiis animi sapiente delectus porro.</p><p>Ullam sit fugiat ducimus ut expedita voluptates. Accusamus ipsum dolorem quia amet consequatur non.</p><p>Eligendi illo hic dolore et qui qui. Adipisci debitis laboriosam aspernatur ad. Harum facere iure quia id voluptas.</p><p>Et tenetur tempora assumenda corporis. Accusamus nemo voluptatibus ratione excepturi. Quia minus qui quos animi dolores voluptatibus facilis. Blanditiis aut cumque commodi.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(16, 3, 1, 'Aut odio eaque et.', 'incidunt-molestiae-quidem-necessitatibus-ut-qui-aut', 'Commodi excepturi consequatur omnis ratione sapiente sed sapiente. Iusto sapiente molestiae nam ipsa molestias eum. Aperiam minus necessitatibus et aperiam assumenda voluptate consequatur.', '<p>Nulla fugit earum mollitia quis. Saepe et adipisci voluptatem laboriosam vero. Et rerum aut debitis cumque veritatis quae odio. Dicta qui quisquam quia velit.</p><p>Natus veritatis commodi et aut. Quia blanditiis aut quod assumenda et quia. Officiis et itaque dolores voluptas.</p><p>Ut numquam ut ut in qui. Porro est consequatur quos vero accusamus. Reprehenderit nobis tempore quaerat esse explicabo velit. Ut necessitatibus ipsum sapiente saepe.</p><p>Cupiditate nihil rem est atque et enim et. Nisi unde quae necessitatibus cumque amet. Quia sit consequatur accusantium. Quo accusamus cumque dolor amet natus dolor.</p><p>Est sunt temporibus aliquam eos odit. Omnis ut doloremque ea unde dignissimos omnis asperiores vel. Distinctio quasi voluptatibus et libero. Aperiam esse fugit voluptatibus eum.</p><p>Aperiam possimus quae accusamus cum et. Sint delectus fugiat voluptas accusamus. Et quia reprehenderit non. Est ullam eveniet quae iste quae.</p><p>Et odit iste aspernatur. Et necessitatibus ipsam voluptatum at et perspiciatis quod. Sit magnam quod consectetur nam dolor qui.</p><p>Repellendus eaque veniam non aliquid non numquam. Aut placeat maxime autem deserunt provident consequatur porro. Harum minus sunt voluptas vel.</p><p>Maxime nihil ducimus ut. Delectus et eligendi nostrum repellendus. Nisi dicta quia mollitia tempora et.</p><p>Esse molestias quo ad fuga. Eum ullam sunt corporis repellendus adipisci temporibus iure. Qui dolores voluptatum nisi quod dolores nemo voluptatem. Quidem iste voluptatem est et in autem architecto.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(17, 3, 3, 'Quo suscipit repellendus cumque repudiandae excepturi.', 'vel-in-commodi-dolorem-velit-aliquam-illum-dignissimos-quisquam', 'Dolores eveniet voluptatibus sint maiores incidunt amet debitis. Praesentium corrupti odio est quasi. Id quis id quia voluptas laudantium nulla nam. Neque rerum aliquid rerum labore omnis id.', '<p>Illum suscipit aspernatur ipsum quis aut. Et enim exercitationem et rerum error autem. Nesciunt omnis quae recusandae sequi. Ut autem minima eligendi corrupti.</p><p>Ea ut fuga eum aut accusamus odio. Est voluptate facere sit perferendis laudantium quisquam perferendis. Eius hic exercitationem impedit expedita in consequatur. Tempore enim et voluptatem quam iusto ut.</p><p>Eos labore expedita quam qui soluta. Est in voluptatem et molestiae animi doloremque sit. Similique nisi omnis itaque cumque consequatur est nulla. Est aperiam officiis dolorem doloremque. Consequatur aliquid nam exercitationem.</p><p>Pariatur pariatur aut quo voluptas placeat et. Et sequi aliquam optio omnis dolores asperiores autem eos. Nisi dolores reprehenderit natus id optio laboriosam officia. Autem sunt et optio ad ea sunt neque ut. Fuga earum quia quis omnis ex iure consequatur.</p><p>Omnis expedita quia numquam earum. Eaque aut minus qui dolores magni quisquam eius ea. Adipisci accusamus debitis et quia. Voluptas eos aliquid quod cupiditate quis iste.</p><p>Qui voluptas dolor dolore maiores fuga molestias. Dolorem accusantium soluta aut sit. Ipsum at est inventore labore nobis corrupti cum.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(18, 3, 3, 'Sed dignissimos et.', 'voluptas-autem-itaque-cumque-et-illum-nobis', 'Corporis reiciendis molestiae labore excepturi. Et ipsa molestias inventore alias. Omnis ea aut nesciunt explicabo. Est et ea enim temporibus voluptas.', '<p>Recusandae sit cumque magnam nihil non corrupti. Inventore qui delectus aliquid placeat. Expedita illo aut fuga. Ex beatae et dignissimos nemo.</p><p>Minus odit autem iusto. Et iusto quibusdam eos quos. Qui ut aliquam autem cupiditate enim vel. Beatae repellat omnis est ullam veniam corrupti.</p><p>Recusandae fugit enim explicabo nulla doloribus id impedit architecto. Soluta magni quis et inventore. Rerum dignissimos laboriosam sit et qui et.</p><p>Alias ut quidem quibusdam quam beatae. Sit ex earum adipisci veritatis quisquam. Necessitatibus harum sed tempora architecto voluptas pariatur eum similique. Voluptatem nihil quia commodi.</p><p>Cumque vitae unde dolorem aut dolores. Aut modi voluptate accusamus minima voluptatem. A tempora itaque occaecati dolorem ut exercitationem. Cupiditate et eveniet tenetur qui.</p><p>Ipsum quo non voluptatum. Sequi dolores expedita et quo. Quas consectetur omnis fuga perspiciatis suscipit et odio. Culpa asperiores tenetur illum incidunt.</p><p>Recusandae dolorem ex est neque aut facere earum. Deserunt voluptas asperiores aperiam quasi magnam. Est consequuntur quia amet dolores. Delectus suscipit tempore vel cum voluptas voluptatum adipisci.</p><p>Cumque fugit quis esse aut maiores. Perferendis consequatur consequatur quaerat eos. Inventore accusantium provident voluptatem neque. Minus pariatur laborum vitae sint et est blanditiis.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(19, 2, 1, 'Et corrupti rem atque.', 'dolorem-numquam-et-non-est-vitae-et', 'Temporibus similique autem voluptatem quam dolores qui. Minima odit impedit nam consectetur dolorem iste aspernatur. Laborum libero velit et et est. Qui voluptas sint dolorum.', '<p>Laudantium suscipit modi rerum assumenda impedit autem est. Et odit veritatis saepe rerum nihil totam. Sint tenetur molestiae accusamus quis.</p><p>Aspernatur quisquam unde fugit omnis quas aut consectetur. Voluptatem dicta quos reiciendis eum tempore ut dolorem. Porro ex reiciendis ducimus ea. Voluptatum et et esse hic incidunt commodi eos.</p><p>Iusto quo sequi nostrum necessitatibus eos vel. Et aut labore labore quod maxime voluptatem mollitia. Quasi praesentium nemo omnis illum et commodi nihil inventore.</p><p>Illo temporibus voluptatem libero. Praesentium consequatur perspiciatis voluptas sint. Omnis dignissimos voluptatum cum sed illum. Modi est consequatur et dolorem qui est.</p><p>Rerum ratione et sed quisquam. Amet vel mollitia laudantium quam eum libero qui voluptas. Repellat labore omnis consequatur facilis est corrupti aut dolorem. Voluptatum ut fugiat et consequatur sit sunt voluptas. Ea ad inventore cumque tempore.</p><p>Occaecati qui vitae eveniet aut. Earum eos voluptas incidunt molestiae ex consequatur saepe. Autem ipsa tempora dolore possimus sit. Molestiae molestiae dolor alias.</p><p>In ducimus numquam modi laboriosam porro aperiam dolores. Quas et enim est explicabo. Tenetur iste commodi eaque eius totam eius ea esse. Consequuntur alias assumenda ut eum et quisquam doloribus.</p><p>Id soluta minima aut eius perferendis. Aperiam vel dolorem aut tempora aliquam.</p><p>Veniam qui cupiditate dolores dolor quia. Odio reiciendis id ut laborum. Voluptas modi repellat aut est fugit. Dolorum porro autem aut sunt sequi.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(20, 3, 3, 'Quibusdam ratione velit.', 'non-molestias-a-et-quasi-saepe-labore-molestiae-qui', 'Numquam qui est quam necessitatibus ad rerum. Voluptate ut sed ut voluptatem molestiae doloremque voluptatem consequatur. Impedit ipsa ab beatae ducimus harum.', '<p>Voluptatum exercitationem perspiciatis facilis et aut. Dicta harum facilis voluptas corporis. Quis magni aliquam delectus rerum dolor eius rerum. Delectus ducimus odio voluptatem voluptates molestias. Autem commodi adipisci voluptas fuga odit.</p><p>Explicabo aut ea dicta consectetur fugiat eum. Eos consequatur eum repudiandae laborum.</p><p>Reprehenderit necessitatibus provident consequatur mollitia porro. Beatae laboriosam dolorum fugiat sequi est vel. Occaecati inventore omnis qui sit sit minima vero ab. Qui qui beatae adipisci corporis qui blanditiis.</p><p>Quisquam velit voluptas qui molestias in molestiae unde non. Impedit dolorem ut quisquam dicta ipsam deserunt. Aliquam magni in deleniti maxime quis eum dolor aut. Neque quasi eaque voluptas rem nisi sunt.</p><p>Sint repellendus sint sint ullam iste sunt dolorem. Dolores rem sed repudiandae dolorum porro dolorem. Iste debitis voluptate dolorum temporibus. Consequuntur ut sed blanditiis consequuntur omnis temporibus expedita et. Quia atque iusto culpa.</p><p>Expedita quod ut autem ut earum atque corporis atque. Saepe sed et quia et corporis est aut. Est atque corporis tenetur atque. Laborum in quibusdam voluptate molestias dicta maiores quasi.</p>', NULL, '2023-10-31 09:25:18', '2023-10-31 09:25:18');

-- Dumping structure for table wpu_blog.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_username_unique` (`username`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table wpu_blog.users: ~2 rows (approximately)
INSERT IGNORE INTO `users` (`id`, `name`, `username`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
	(1, 'Ulva Prastuti', 'zjailani', 'nova.pudjiastuti@example.org', '2023-10-31 09:25:18', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Q3qNR4bej5', '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(2, 'Eva Jessica Nurdiyanti', 'puti.iswahyudi', 'maulana.endra@example.net', '2023-10-31 09:25:18', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 't1cPaTWdHn', '2023-10-31 09:25:18', '2023-10-31 09:25:18'),
	(3, 'Julia Yessi Pudjiastuti', 'karen47', 'cinta34@example.org', '2023-10-31 09:25:18', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '4dYOEBZ4Lg', '2023-10-31 09:25:18', '2023-10-31 09:25:18');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
